<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>git-blame</string>
	</array>
	<key>name</key>
	<string>SublimeGit Blame</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.git-blame.boundary</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.hex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.git-blame.file</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.paren</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.other.git-blame.author</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.date</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.paren</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\^)? ?(0+) (.+)? ?(\()(Not Committed Yet)  (\w+ \w+ \d+ \d\d:\d\d:\d\d \d{4})(\)) (.*)</string>
			<key>name</key>
			<string>meta.git-blame.notcommitted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.git-blame.boundary</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.git-blame.hex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.git-blame.file</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.paren</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.type.git-blame.author</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.date</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.other.git-blame.paren</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>text</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\^)? ?([0-9a-f]+) (.+)? ?(\()(.+)  (\w+ \w+ \d+ \d\d:\d\d:\d\d \d{4})(\)) (.*)</string>
			<key>name</key>
			<string>meta.git-blame.line</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.git-blame</string>
	<key>uuid</key>
	<string>c069541f-b5d7-4fdf-8c1c-88a3d77b4de9</string>
</dict>
</plist>
