<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>COMMIT_EDITMSG</string>
	</array>
	<key>name</key>
	<string>SublimeGit Commit Message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.git-commit.branch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# On branch (.*)\n</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.git-commit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.git-commit.remote.ahead</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.git-commit.remote.name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.git-commit.remote.ahead</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.git-commit.remote.num-commits</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*# Your branch is )(ahead of ')(.+)(' by )(\d+ .+)\.\n</string>
			<key>name</key>
			<string>meta.git-commit.remote.status</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.git-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Changes to be committed:)</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.git-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Changes not staged for commit:)</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.git-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Untracked files:)</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.deleted.warning.git-commit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (warning:.+)</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.git-commit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.git-commit.status</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.git-commit</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.other.git-commit.file</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?:#   )|(?:#	))(.+:)(\s+)(.+)</string>
			<key>name</key>
			<string>meta.git-commit.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#(.*)</string>
			<key>name</key>
			<string>comment.line.number-sign.git-commit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.git-diff</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.git-commit</string>
	<key>uuid</key>
	<string>803661a4-a9b6-4945-b061-f96f26dd4e84</string>
</dict>
</plist>
